matrix:
  include:
    - language: python
      python: 
        - "3.6"
      node_js:
        - "node"
      env:
        - FLASK=1.0.2
      install:
        - pip3 install Flask==$FLASK
        - pip3 install -r requirements.txt
        - pip3 install -e .
      before_script:
        - chmod +x .travis/writetoenv.sh && ./.travis/writetoenv.sh
        - chmod +x .travis/deploy.sh
      script:
        - pylint server
        # - nosetests
      after_success:
        - ./.travis/deploy.sh

    - language: node_js
      node_js:
        - "node"
        - "8"
      install:
        - yarn add eslint
        - yarn install
        - cd client/ && yarn install
      before_script:
        - cd ../ && yarn db-rewrite
      script:
        - cd client/ && yarn lint --ext .js,.vue
        - yarn build
      cache:
        directories:
          - "node_modules"
          - "client/node_modules"
